src/main/java/com/example/lastfresh/controller/SellController.java, src/main/resources/static/front/assets/css/sell.css, src/main/resources/templates/sell/pos.html
=> html, css, 컨트롤러

src/main/resources/templates/myPage/InformationCorrection.html, src/main/resources/templates/myPage/ModifyPersonalInformation.html, src/main/resources/templates/myPage/OrderDetails.html, src/main/resources/templates/myPage/OrderHistory.html, src/main/resources/templates/myPage/ProductReview.html, src/main/resources/templates/myPage/assets/css/InformationCorrection.css, src/main/resources/templates/myPage/assets/css/ModifyPersonalInformation.css, src/main/resources/templates/myPage/assets/css/OrderDetails.css, src/main/resources/templates/myPage/assets/css/OrderHistory.css, src/main/resources/templates/myPage/assets/css/myPageMenuBar.css
=> 상품목록, 상세내역, 개인정보 수정 커밋

src/main/java/com/example/lastfresh/ProductController.java, src/main/resources/static/front/assets/css/product.css, src/main/resources/static/front/assets/css/productDetail.css, src/main/resources/templates/productList/newProduct.html, src/main/resources/templates/productList/productDetail.html
=> 상품 목록, 상품상세페이지

src/main/resources/templates/pixelarityTemplate/userJoin.html
=> 회원가입 프론트-현진용

src/main/resources/static/front/assets/css/sell.css, src/main/resources/static/front/assets/js/sell/pos.js, src/main/resources/templates/sell/pos.html
=> 현재까지 진행 상황

src/main/resources/templates/user/idFind.html, src/main/resources/templates/user/pwFind.html, src/main/resources/templates/user/pwSetup.html, src/main/resources/templates/user/userJoin.html, src/main/resources/templates/user/userLogin.html
현진용-프론트 수정(회원가입,로그인,비번 아아디찾기, 비밀번호 재설정)
=> 프론트 수정(회원가입,로그인,비번 아아디찾기, 비밀번호 재설정)

src/main/resources/static/front/assets/css/product.css, src/main/resources/static/front/assets/css/productDetail.css, src/main/resources/templates/productList/delivery.html, src/main/resources/templates/productList/pickup.html, src/main/resources/templates/productList/productDetail.html, src/main/resources/templates/productList/shipping.html
=> 모달창/우리 동네 배달/택배 배달/픽업

src/main/resources/templates/myPage/InformationCorrection.html, src/main/resources/templates/myPage/OrderDetails.html, src/main/resources/templates/myPage/OrderHistory.html, src/main/resources/templates/myPage/ProductReviewAfterList.html, src/main/resources/templates/myPage/ProductReviewBeforeList.html, src/main/resources/templates/myPage/ReviewWrite.html, src/main/resources/templates/myPage/assets/css/InformationCorrection.css, src/main/resources/templates/myPage/assets/css/ModifyPersonalInformation.css, src/main/resources/templates/myPage/assets/css/OrderDetails.css, src/main/resources/templates/myPage/assets/css/OrderHistory.css, src/main/resources/templates/myPage/assets/css/ProductReviewAfterList.css, src/main/resources/templates/myPage/assets/css/ProductReviewBeforeList.css, src/main/resources/templates/myPage/assets/css/ReviewWrite.css, src/main/resources/templates/myPage/assets/css/myPageMenuBar.css
=> 도윤 반응형, 마이페이지 css,html 수정

src/main/resources/templates/user/idFind.html, src/main/resources/templates/user/pwFind.html, src/main/resources/templates/user/pwSetup.html, src/main/resources/templates/user/userJoin.html, src/main/resources/templates/user/userLogin.html
=> 현진용-프론트 최종(회원가입,로그인,비밀번호재설정,아이디찾기,비밀번호 찾기)

src/main/java/com/example/lastfresh/controller/MainPageController.java, src/main/resources/static/front/assets/css/cart.css, src/main/resources/static/front/assets/css/cartOrder.css, src/main/resources/static/front/assets/css/main.css, src/main/resources/static/front/assets/css/mainPage.css, src/main/resources/templates/mainPage/cart.html, src/main/resources/templates/mainPage/howTo.html, src/main/resources/templates/mainPage/main.html, src/main/resources/templates/mainPage/order.html
=> 메인페이지 제외 다른 페이지 자바스크립트 까지 완료

src/main/resources/templates/mainPage/main.html
=> 메인페이지 반응형 수정

src/main/resources/static/front/assets/js/sell/menuRegister.js
=> v1 자바스크립트 수정

src/main/resources/static/front/assets/css/cart.css, src/main/resources/static/front/assets/css/mainPage.css, src/main/resources/templates/mainPage/cart.html, src/main/resources/templates/mainPage/main.html
=> 메인페이지, 장바구니 반응형

src/main/resources/static/riderFront/assets/css/main.css
=> 라이더 main css

src/main/java/com/example/lastfresh/controller/product/ProductController.java, src/main/java/com/example/lastfresh/controller/rider/RiderController.java, src/main/resources/static/front/assets/js/product/proDetail.js, src/main/resources/templates/product/proDelivery.html, src/main/resources/templates/product/proDetail.html, src/main/resources/templates/product/proNew.html, src/main/resources/templates/product/proPickup.html, src/main/resources/templates/product/proShipping.html, src/main/resources/templates/rider/riderList.html, src/main/resources/templates/rider/riderMy.html
헤더주석처리 rider, product Controller추가
=> 헤더주석처리 rider, product Controller추가

src/main/resources/templates/user/manage/userJoin.html
=> 현진용 -프론트 반응형 완성(로그인,회원가입)

src/main/java/com/example/lastfresh/service/user/UserFindService.java, src/main/resources/static/front/assets/css/user/userFindId.css, src/main/resources/static/front/assets/css/user/userNewPw.css, src/main/resources/static/front/assets/js/user/userFind.js, src/main/resources/static/front/assets/js/user/userFindPw.js, src/main/resources/templates/user/manage/userFindId.html, src/main/resources/templates/user/manage/userFindPw.html
=> userFindId, userFindFw수정

src/main/java/com/example/lastfresh/controller/user/UserManaingController.java, src/main/java/com/example/lastfresh/domain/repository/UserRepository.java, src/main/java/com/example/lastfresh/domain/vo/UserVO.java, src/main/java/com/example/lastfresh/service/user/UserService.java, src/main/resources/static/front/assets/css/user/userJoin.css, src/main/resources/static/front/assets/js/user/userJoin.js, src/main/resources/static/front/assets/js/user/userSelect.js, src/main/resources/templates/user/manage/userJoin.html, src/main/resources/templates/user/manage/userSelect.html
=> 회원가입(유효성검사,핸드폰인증,암호화 미구현)

pom.xml, src/main/java/com/example/lastfresh/Hyun/WebSecurityConfig.java, src/main/java/com/example/lastfresh/controller/user/UserManaingController.java, src/main/java/com/example/lastfresh/service/user/UserService.java, src/main/resources/static/front/assets/js/user/userJoin.js, src/main/resources/templates/user/manage/userJoin.html
=> 회원가입(인증,암호화)

src/main/java/com/example/lastfresh/controller/sell/PosController.java, src/main/java/com/example/lastfresh/controller/sell/ResponseEntityEx.java, src/main/java/com/example/lastfresh/domain/dao/owner/PosDAO.java, src/main/java/com/example/lastfresh/domain/dto/PosDTO.java, src/main/java/com/example/lastfresh/domain/dto/PosPageDTO.java, src/main/java/com/example/lastfresh/mapper/owner/PosMapper.java, src/main/java/com/example/lastfresh/service/owner/PosService.java, src/main/resources/mapper/owner/PosMapper.xml, src/main/resources/static/front/assets/css/sell/sell.css, src/main/resources/static/front/assets/js/sell/menuRegister.js, src/main/resources/static/front/assets/js/sell/pos.js, src/main/resources/static/front/assets/js/sell/sellMain.js, src/main/resources/templates/sell/pos.html, src/main/resources/templates/sell/sellMain.html, src/test/java/com/example/lastfresh/service/owner/PoaServiceTest.java
=> feat:주문 상태에 따른 페이지 구현, 페이징 처리 완료

src/main/java/com/example/lastfresh/controller/main/MainPageController.java, src/main/java/com/example/lastfresh/controller/user/UserManaingController.java, src/main/java/com/example/lastfresh/service/user/UserService.java, src/main/resources/templates/fragments/header.html, src/main/resources/templates/fragments/headerWithout.html, src/main/resources/templates/user/manage/userLogin.html
=> 현진용(페이지이동,세션)

src/main/java/com/example/lastfresh/controller/main/MainPageController.java, src/main/java/com/example/lastfresh/controller/user/UserManaingController.java, src/main/java/com/example/lastfresh/controller/user/UserMyPageController.java, src/main/resources/templates/fragments/header.html, src/main/resources/templates/rider/riderList.html
=> 현진용_카카오 수정

src/main/java/com/example/lastfresh/controller/user/BasketController.java, src/main/java/com/example/lastfresh/controller/user/UserMyPageController.java
=> updated controllers

src/main/resources/static/front/assets/js/user/userNewPw.js
=> 패스워드 수정 알럿
